import type { ProductCardData } from '@/components/ProductCard'

export const MY_SHOP_PRODUCTS: ProductCardData[] = [
  {
    _id: 'myshop-mk',
    name: '檀香粉(含黏粉)150g',
    slug: 'mk',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/dqpOVABK324oAxeLNrkRwEv7/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/MK',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$50',
    shortDescription: '限量 10 包',
  },
  {
    _id: 'myshop-hku',
    name: '【精品收藏】台灣黃檜木手串',
    slug: 'hku',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/j7m6e8BLYJARbRWwNaG5RKMX/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/HKU',
    productType: 'beads',
    origin: '商城現貨',
    priceLabel: 'NT$1,020 - 4,400',
    shortDescription: '社群限量產品',
    isCollectible: true,
  },
  {
    _id: 'myshop-kundian-powder',
    name: '頂級坤甸沉香粉20g',
    slug: 'kundian-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/g1JZGpdVYBmBDdKAN0onavMR/600x.png',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/坤甸粉',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$2,000 - 5,100',
    shortDescription: '僅商城販售',
    isCollectible: true,
  },
  {
    _id: 'myshop-gubang-incense',
    name: '古邦老檀香臥香10g',
    slug: 'gubang-incense',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/Kyg9vWx8NyKyaMj83GJP14Zm/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/古邦臥香',
    productType: 'incense-stick',
    origin: '商城現貨',
    priceLabel: 'NT$350 - 899',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-tonga-incense',
    name: '東加老山檀香臥香10g',
    slug: 'tonga-incense',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/zRo4LO6m3AmADPmX3pr2d90e/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/東加臥香',
    productType: 'incense-stick',
    origin: '商城現貨',
    priceLabel: 'NT$350 - 899',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-laoshan-powder',
    name: '正老山檀香抽油粉 600g',
    slug: 'laoshan-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/7QBw2oEnYzJv42n4YxAP0vM9/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/老山抽600g',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$250 - 600',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-africa-sandalwood-coil',
    name: '非洲檀香小盤香4H',
    slug: 'africa-sandalwood-coil',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/BW4907rb3bPQP4ZxNQGK6kwy/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/非洲檀香4H',
    productType: 'incense-stick',
    origin: '商城現貨',
    priceLabel: 'NT$250 - 999',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-irian-extract-powder',
    name: '伊利安沉香抽油粉 600g',
    slug: 'irian-extract-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/1LPZao453vJLJeoo3QAR86mM/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/伊利安抽',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$450 - 1,200',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-malaok-powder',
    name: '特級馬拉OK沉香粉200g',
    slug: 'malaok-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/Xno5Qb1D3MVgrnM0l67ZWPv9/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/特級馬拉OK200g',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$500 - 799',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-taiwan-cypress-powder',
    name: '台灣肖楠粉600g',
    slug: 'taiwan-cypress-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/o7KQGvx83OMyqz4zNnVR9Xkj/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/台灣肖楠粉',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$250 - 399',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-irian-soil-powder',
    name: '伊利安土沉粉100g',
    slug: 'irian-soil-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/Xno5Qb1D3MVgr4O1l67ZWPv9/600x.png',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/伊利安土沉粉',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$600 - 999',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-africa-sandalwood-powder',
    name: '非洲老山檀香粉600g',
    slug: 'africa-sandalwood-powder',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/Wqybvx25N9yRGQbMNREOMVPo/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/非洲檀香粉',
    productType: 'raw-material',
    origin: '商城現貨',
    priceLabel: 'NT$250 - 399',
    shortDescription: '僅商城販售',
  },
  {
    _id: 'myshop-indonesia-jiangzhen-coil',
    name: '印尼降真小盤香4H',
    slug: 'indonesia-jiangzhen-coil',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/nMRpQ02P3XERKg8Rlr7BkJaE/600x.png',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/印尼降真小盤香',
    productType: 'incense-stick',
    origin: '商城現貨',
    priceLabel: 'NT$88',
    shortDescription: '新品上架',
  },
  {
    _id: 'myshop-green-kinam-incense',
    name: '特級高油嫁接綠棋楠立香100g',
    slug: 'green-kinam-incense',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/ZOaL8DPWY6LRqq25l92ExyG0/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/特級綠棋楠立香100g',
    productType: 'incense-stick',
    origin: '商城現貨',
    priceLabel: 'NT$660',
    shortDescription: '限量商品，群友特惠加購',
  },
  {
    _id: 'myshop-agarwood-spray-lotion',
    name: '沉香噴霧乳液',
    slug: 'agarwood-spray-lotion',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/7QBw2oEnYzJ4eaWGYxAP0vM9/600x.jpg',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/沉香噴霧乳液',
    productType: 'other',
    origin: '商城現貨',
    priceLabel: 'NT$399 - 1,750',
    shortDescription: '已銷售超過 1500 罐',
  },
  {
    _id: 'myshop-plectranthus-soap',
    name: '左手香舒活清膚皂',
    slug: 'plectranthus-soap',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/DPq15dgL3PqwbaZElrBbJ2am/600x.png',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/左手香皂蝸牛滋養皂-0zhbta',
    productType: 'other',
    origin: '商城現貨',
    priceLabel: 'NT$150',
    shortDescription: '限量商品',
  },
  {
    _id: 'myshop-snail-soap',
    name: '左手香蝸牛滋養皂',
    slug: 'snail-soap',
    mainImageUrl: 'https://img.1shop.tw/k3xVqyrnXN2qrJRBZKbomdGD/kEyLdZjRNLmwVr6nY8pWbz6O/600x.png',
    externalUrl: 'https://baujie-agarwood.my1shop.com/products/左手香皂蝸牛滋養皂',
    productType: 'other',
    origin: '商城現貨',
    priceLabel: 'NT$180',
    shortDescription: '限量商品',
  },
]
